#!/bin/bash
set -eo pipefail

echo "**** Starting Couchpotato (https://couchpota.to/) container. Enjoy! ****"
[ -n "$OPEN_FILE_LIMIT" ] &&\
  ulimit -n $OPEN_FILE_LIMIT

dockerize \
  -template /templates/Procfile.tpl:/Procfile \
  -template /templates/dnsmasq.conf.tpl:/etc/dnsmasq.conf \
  echo "==> Writing configs"

exec $*
exit 0