#!/bin/bash
set -eo pipefail

echo "**** Starting Couchpotato (https://couchpota.to/) container. Enjoy! ****"
[ -n "$OPEN_FILE_LIMIT" ] &&\
  ulimit -n $OPEN_FILE_LIMIT

dockerize \
  -template /templates/supervisord.conf.tpl:/etc/supervisor/supervisord.conf \
  echo "==> Writing /etc/supervisor/supervisord.conf from /templates/supervisord.conf.tpl"

exec $*
exit 0