#!/bin/bash
set -eo pipefail
trap "exit 0" 2 15

cd $COUCHPOTATO_HOME
git checkout $COUCHPOTATO_CHANNEL
git pull

. /venv/bin/activate
export PYTHONPATH=$COUCHPOTATO_HOME
exec -a "supervisord" -l "supervisord" "-c" "/etc/supervisord.conf"
exit 0