#!/bin/bash
set -eo pipefail

echo "**** Starting Couchpotato (https://couchpota.to/) container. Enjoy! ****"
[ -n "$OPEN_FILE_LIMIT" ] &&\
  ulimit -n $OPEN_FILE_LIMIT

dockerize \
  -template /templates/supervisord.conf.tpl:/etc/supervisord.conf \
  -template /templates/dnsmasq.conf.tpl:/etc/dnsmasq.conf \
  echo "==> Writing configs from templates"

dnsmasq --all-servers --local-service
exec $*
exit 0